# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5102b2fb8f93575778a063d24be5d15bfa677879d56296d95d7ffbeaafc5c9836ba3fe6d17338060560c1842d65b2fa778e427026e479c4a57235ba628dd368e

test:
  secret_key_base: 6d170b31bced507d9e9ed04d40d69e925359d0a5711f796ef3721fd6913644b82d14dc904a938388cae1c0da77679d77fcf8b2a5ad2d631128699adc05e52da9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
